### PR TITLE
Created echo color fix branch

### LINKED ISSUE #242: Improve output of the echo server
Currently the output of the echo server is very verbose and hard to read. We'd like to experiment with a more structured output, perhaps with color to help users debug issues using the echo server.

### PR DESCRIPTION
**Pull request by Weeblin**
This adds colours to echo sever output.
fixes #242 

Signed-off-by: wenlin <wenlin.yi@jetstack.io>

### CODE REVIEW

File: pkg/echo/echo.go [hunk 1]
```diff
@@ -43,12 +44,20 @@ func echoHandler(w http.ResponseWriter, r *http.Request) {
 	}
 
 	// print the data sent to the echo server to the console
-	fmt.Printf("-- %s %s -> created %d\n", r.Method, r.URL.Path, http.StatusCreated)
+
+	// this should be in color1
```
Comment (j-fuentes) [inline pkg/echo/echo.go:48]: you can remove these `// this should be color ...` comments

File: pkg/echo/echo.go [hunk 2]
```diff
@@ -43,12 +44,20 @@ func echoHandler(w http.ResponseWriter, r *http.Request) {
...
+	// this can stay in default color
 	fmt.Printf("received %d readings:\n", len(payload.DataReadings))
-	for _, r := range payload.DataReadings {
-		fmt.Printf("%+v\n", r)
+	for i, r := range payload.DataReadings {
+		if i%2 == 0 {
+			color.Yellow("Reading:\n%s\n", prettyPrint(r))
+		} else {
+			color.Cyan("Reading:\n%s\n", prettyPrint(r))
+		}
```
Comment (j-fuentes) [inline pkg/echo/echo.go:57]: nit. I'd rework this a bit to avoid repetition and always print in the same line:

```
for i, r := range payload.DataReadings {
  c := color.New(color.FgYellow)
  if i%2==0 {
    c = color.New(color.Cyan)
  }
  color.New(c).Fprintf("#%s:\n%s\n", i, prettyPrint(r))
}
```
